# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2OLqMk757kEzIEqUiqJjtqTxl2LJ6LX
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import xgboost as xgb
from tensorflow.keras.models import load_model
from datetime import datetime, timedelta
from PIL import Image
import requests
import os

# Helper function to download files from GitHub
def download_file(url, filename):
    response = requests.get(url)
    with open(filename, 'wb') as f:
        f.write(response.content)

# Download models from GitHub if they don't exist
if not os.path.exists("xgboost_full_model.json"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/xgboost_full_model.json", "xgboost_full_model.json")
if not os.path.exists("lstm_full_model.h5"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/lstm_full_model.h5", "lstm_full_model.h5")
if not os.path.exists("svm_full_model.pkl"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/svm_full_model.pkl", "svm_full_model.pkl")
if not os.path.exists("scaler_X.pkl"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/scaler_X.pkl", "scaler_X.pkl")
if not os.path.exists("scaler_y.pkl"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/scaler_y.pkl", "scaler_y.pkl")
if not os.path.exists("scaler.pkl"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/scaler.pkl", "scaler.pkl")

# Load models and scalers
xgb_model = xgb.Booster()
xgb_model.load_model("xgboost_full_model.json")
lstm_model = load_model("lstm_full_model.h5")
svm_model = joblib.load("svm_full_model.pkl")
scaler_X = joblib.load("scaler_X.pkl")
scaler_y = joblib.load("scaler_y.pkl")
scaler = joblib.load("scaler.pkl")

# Download images from GitHub if they don't exist
if not os.path.exists("banner_image.png"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/Screenshot%202024-07-03%20135327.png", "banner_image.png")
if not os.path.exists("bearish.png"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/Bearish.png", "bearish.png")
if not os.path.exists("bullish.png"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/Bullish.png", "bullish.png")
if not os.path.exists("neutral.png"):
    download_file("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/Neutral.png", "neutral.png")

# Load images
banner_image = Image.open("banner_image.png")
bearish_image = Image.open("bearish.png")
bullish_image = Image.open("bullish.png")
neutral_image = Image.open("neutral.png")

# Helper functions
def create_lagged_features(data, num_lags=10):
    for i in range(1, num_lags + 1):
        data[f'lag_{i}'] = data['Close'].shift(i)
    data.dropna(inplace=True)
    return data

def predict_xgb(date, data):
    data = create_lagged_features(data)
    features = data[[f'lag_{i}' for i in range(1, 11)]].iloc[-1]
    dmatrix = xgb.DMatrix(features.values.reshape(1, -1))
    pred = xgb_model.predict(dmatrix)
    return scaler_y.inverse_transform(pred.reshape(-1, 1))[0, 0]

def predict_lstm(date, data):
    data = create_lagged_features(data)
    features = scaler.transform(data[['Close']].values[-60:])
    pred = lstm_model.predict(features.reshape(1, 60, 1))
    return scaler.inverse_transform(pred)[0, 0]

def classify_trend(rsi):
    if rsi > 70:
        return 'Bullish', bullish_image
    elif rsi < 30:
        return 'Bearish', bearish_image
    else:
        return 'Neutral', neutral_image

def calculate_rsi(data, period=14):
    delta = data['Close'].diff()
    gain = (delta.where(delta > 0, 0))
    loss = (-delta.where(delta < 0, 0))
    avg_gain = gain.rolling(window=period, min_periods=1).mean()
    avg_loss = loss.rolling(window=period, min_periods=1).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi.iloc[-1]

def predict_trend_with_rsi(date, data):
    predicted_close = predict_lstm(date, data)
    data = data.append({'Date': date, 'Close': predicted_close}, ignore_index=True)
    latest_rsi = calculate_rsi(data)
    return classify_trend(latest_rsi)

def validate_date(selected_date):
    if selected_date.weekday() >= 5:
        st.error("Select the trading days only")
        return False
    return True

# Streamlit UI
st.image(banner_image, use_column_width=True)
st.write("## Tata Motors Limited (TATAMOTORS.NS)")
st.write("It offers its products to fleet owners, transporters, government agencies, defense, public transport utilities, small and medium enterprises (SMEs), agriculture and rural segment, mining and construction industry, etc. The company was incorporated in 1945 and is headquartered in Mumbai, India.")

min_date = datetime.today() + timedelta(days=1)
max_date = min_date + timedelta(days=3650)  # 10 years from today

selected_date = st.date_input("Select a date", min_value=min_date, max_value=max_date, value=min_date)
forecast_type = st.radio("Forecast Type", ('Short term', 'Long term'))

if st.button("Apply"):
    if validate_date(selected_date):
        data = pd.read_csv("https://github.com/Divya-coder-isb/FP2_Epiqo/raw/main/tatamotors_historical_data.csv")
        data['Date'] = pd.to_datetime(data['Date'])
        data.set_index('Date', inplace=True)
        if forecast_type == 'Short term':
            price = predict_xgb(selected_date, data)
            st.write(f"Short term Adj closing price: {price} INR")
        else:
            price = predict_lstm(selected_date, data)
            st.write(f"Long term Adj closing price: {price} INR")

        trend, trend_image = predict_trend_with_rsi(selected_date, data)
        st.write(f"Market Trend: {trend}")
        if trend_image:
            st.image(trend_image, width=100)

# Display date in the box
st.write(f"Selected Date: {selected_date}")